version: '3'
services:
  frontend: 
    container_name: lazycup-fe
    build:
      context: ./frontend 
    ports: 
      - "5173:5173"
    restart: always
    depends_on:
      - backend

  backend: 
    container_name: lazycup-be
    build:
      context: ./backend
    ports:
      - "3030:3030"
    restart: always
    depends_on:
      - db

  db:
    container_name: lazycup-db
    image: mysql:8.3.0
    ports:
    - "3306:3306"
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""